name: Conventional Commit

on:
  pull_request:
    types:
      - edited
      - opened

jobs:
  conventional-commit:
    name: Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Conventional Commit title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            infra
            ci
            docs
            deps
            perf
            refactor
            test
            chore
